In [8]:
import pandas as pd

file_path = "total_data.csv"
df = pd.read_csv(file_path)

# '주차' 컬럼을 날짜 형식으로 변환
df['주차'] = pd.to_datetime(df['주차'], format='%Y%m%d')

# 같은 주차의 같은 소품종일 경우 그룹화 및 합산
grouped_df = df.groupby(['주차', '라인', '성별', '기획년도', '시즌이월', '상품년차', '시즌', '복종', '소품종']).sum(numeric_only=True).reset_index()

# 결과 확인
grouped_df.shape
# df.shape

(22012, 39)

In [10]:
# 주어진 데이터의 최소/최대 날짜 범위 가져오기
date_range = pd.date_range(start=grouped_df['주차'].min(), end=grouped_df['주차'].max(), freq='W')
# date_range # 확인

# 누락된 주차 찾기
missing_weeks = sorted(set(date_range) - set(grouped_df['주차']))

# 누락된 주차 출력
print("누락된 주차:", missing_weeks)

누락된 주차: []

In [35]:
filtered_df = grouped_df[~grouped_df['라인'].isin(['ZD', 'ZE', 'ZF'])]

# grouped_df['소품종'].unique() #37개

# '복종'과 '소품종' 컬럼을 결합하여 새로운 '카테고리' 컬럼 생성
filtered_df['카테고리'] = filtered_df['복종'] + "_" + filtered_df['소품종'] +  "_" + filtered_df['라인'] 
print(sorted(filtered_df['카테고리'].unique()))
# filtered_df['카테고리'].nunique()

['가죽&FUR_가죽점퍼_ZA', '니트 셔츠_라운드(V넥 등)_ZB', '니트 셔츠_라운드_ZA', '니트 셔츠_라운드_ZB', '니트 셔츠_라운드_ZG', '니트 셔츠_오픈형티(맨투맨 등)_ZA', '니트 셔츠_오픈형티(맨투맨 등)_ZB', '니트 셔츠_오픈형티(맨투맨 등)_ZG', '니트 셔츠_티에리_ZA', '니트 셔츠_티에리_ZB', '니트 셔츠_후드티_ZB', '니트 셔츠_후드티_ZG', '데님_데님자켓_ZB', '데님_데님팬츠_ZB', '사파리_패딩사파리_ZA', '사파리_패딩사파리_ZB', '소품_기타_ZA', '소품_벨트_ZB', '소품_신발_ZB', '소품_양말_ZB', '소품_타이_ZA', '수트_블레이져(수트)_ZA', '수트_블레이져(수트)_ZB', '수트_블레이져(수트)_ZC', '수트_수트팬츠_ZA', '수트_수트팬츠_ZB', '수트_수트팬츠_ZC', '스웨터_T-에리_ZA', '스웨터_T-에리_ZB', '스웨터_Turtle_ZA', '스웨터_Turtle_ZB', '스웨터_VEST_ZA', '스웨터_VEST_ZB', '스웨터_라운드_ZA', '스웨터_라운드_ZB', '스웨터_오픈형(CARDIGAN)_ZA', '스웨터_오픈형(CARDIGAN)_ZB', '스웨터_후드T_ZA', '언더웨어_BOTTOM_ZB', '언더웨어_TOP_ZB', '언더웨어_언더웨어 셋업_ZB', '언더웨어_이너웨어 민소매_ZB', '우븐 셔츠_드레스셔츠_ZB', '우븐 셔츠_드레스셔츠_ZC', '우븐 셔츠_캐쥬얼셔츠_ZA', '우븐 셔츠_캐쥬얼셔츠_ZB', '자켓_싱글재킷_ZA', '자켓_싱글재킷_ZB', '점퍼_점퍼_ZA', '점퍼_점퍼_ZB', '점퍼_점퍼_ZG', '점퍼_패딩점퍼_ZB', '조끼_패딩베스트_ZB', '코트_더블코트_ZA', '코트_더블코트_ZB', '코트_싱글코트_ZA', '코트_싱글코트_ZB', '팬츠_니트팬츠_ZA', '팬츠_니트팬츠_ZB', '팬츠_니트팬츠_ZG', '팬츠_반바지_ZA', '팬츠_반바지_ZB', '팬츠_반바지_ZG', '팬츠_팬츠(일반)_ZA', '팬츠_팬츠(일반)_ZB', '팬츠_팬츠(일반)_ZG']

<ipython-input-35-f895d5aa3844>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['카테고리'] = filtered_df['복종'] + "_" + filtered_df['소품종'] +  "_" + filtered_df['라인']

In [33]:
filtered_df.shape

(13649, 40)

In [41]:
# filtered_df['복종'].unique()
filtered2_df = filtered_df[~filtered_df['복종'].isin(['소품', '언더웨어'])]
filtered2_df['카테고리'].nunique()
print(sorted(filtered2_df['카테고리'].unique()))

['가죽&FUR_가죽점퍼_ZA', '니트 셔츠_라운드(V넥 등)_ZB', '니트 셔츠_라운드_ZA', '니트 셔츠_라운드_ZB', '니트 셔츠_라운드_ZG', '니트 셔츠_오픈형티(맨투맨 등)_ZA', '니트 셔츠_오픈형티(맨투맨 등)_ZB', '니트 셔츠_오픈형티(맨투맨 등)_ZG', '니트 셔츠_티에리_ZA', '니트 셔츠_티에리_ZB', '니트 셔츠_후드티_ZB', '니트 셔츠_후드티_ZG', '데님_데님자켓_ZB', '데님_데님팬츠_ZB', '사파리_패딩사파리_ZA', '사파리_패딩사파리_ZB', '수트_블레이져(수트)_ZA', '수트_블레이져(수트)_ZB', '수트_블레이져(수트)_ZC', '수트_수트팬츠_ZA', '수트_수트팬츠_ZB', '수트_수트팬츠_ZC', '스웨터_T-에리_ZA', '스웨터_T-에리_ZB', '스웨터_Turtle_ZA', '스웨터_Turtle_ZB', '스웨터_VEST_ZA', '스웨터_VEST_ZB', '스웨터_라운드_ZA', '스웨터_라운드_ZB', '스웨터_오픈형(CARDIGAN)_ZA', '스웨터_오픈형(CARDIGAN)_ZB', '스웨터_후드T_ZA', '우븐 셔츠_드레스셔츠_ZB', '우븐 셔츠_드레스셔츠_ZC', '우븐 셔츠_캐쥬얼셔츠_ZA', '우븐 셔츠_캐쥬얼셔츠_ZB', '자켓_싱글재킷_ZA', '자켓_싱글재킷_ZB', '점퍼_점퍼_ZA', '점퍼_점퍼_ZB', '점퍼_점퍼_ZG', '점퍼_패딩점퍼_ZB', '조끼_패딩베스트_ZB', '코트_더블코트_ZA', '코트_더블코트_ZB', '코트_싱글코트_ZA', '코트_싱글코트_ZB', '팬츠_니트팬츠_ZA', '팬츠_니트팬츠_ZB', '팬츠_니트팬츠_ZG', '팬츠_반바지_ZA', '팬츠_반바지_ZB', '팬츠_반바지_ZG', '팬츠_팬츠(일반)_ZA', '팬츠_팬츠(일반)_ZB', '팬츠_팬츠(일반)_ZG']

In [ ]:
# filtered2_df.shape
filtered3_df = filtered2_df[['주차','카테고리','판매액','판매수량','매출원가','판매택가']]
filtered3_df

              주차            카테고리       판매액  판매수량      매출원가      판매택가
0     2021-01-03  가죽&FUR_가죽점퍼_ZA  52297400    53  10846000  52947000
1     2021-01-03  수트_블레이져(수트)_ZA  19685400   109   5717811  35131000
2     2021-01-03      수트_수트팬츠_ZA  12921890   128   3853581  23232000
4     2021-01-03    니트 셔츠_라운드_ZB  18981424   401   3559559  28029900
5     2021-01-03  수트_블레이져(수트)_ZB  29890941   194   7913293  38606000
...          ...             ...       ...   ...       ...       ...
22007 2024-12-29    팬츠_팬츠(일반)_ZG    311565     5     85101    645000
22008 2024-12-29    니트 셔츠_라운드_ZG         0     0         0         0
22009 2024-12-29        점퍼_점퍼_ZG         0     0         0         0
22010 2024-12-29       팬츠_반바지_ZG         0     0         0         0
22011 2024-12-29    팬츠_팬츠(일반)_ZG         0     0         0         0

[12582 rows x 6 columns]

In [ ]:
filtered3_df['실판매가'] = filtered3_df['판매액']/filtered3_df['판매수량']

filtered3_df['택가'] = filtered3_df['판매택가']/filtered3_df['판매수량']

filtered3_df['할인율'] = (filtered3_df['택가'] - filtered3_df['실판매가']) / filtered3_df['택가']

filtered3_df.fillna(0, inplace=True)
filtered3_df

<ipython-input-53-78b44506f75e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered3_df['실판매가'] = filtered3_df['판매액']/filtered3_df['판매수량']
<ipython-input-53-78b44506f75e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered3_df['택가'] = filtered3_df['판매택가']/filtered3_df['판매수량']
<ipython-input-53-78b44506f75e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered3_df['할인율'] = (filtered3_df['택가'] - filtered3_df['실판매가']) / filtered3_df['택가']
c:\Users\kjh27\anaconda3\lib\site-packages\pandas\core\frame.py:4462: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

,주차,카테고리,판매액,판매수량,매출원가,판매택가,실판매가,택가,할인율
0,2021-01-03,가죽&FUR_가죽점퍼_ZA,52297400,53,10846000,52947000,986743.396226,999000.000000,0.012269
1,2021-01-03,수트_블레이져(수트)_ZA,19685400,109,5717811,35131000,180600.000000,322302.752294,0.439657
2,2021-01-03,수트_수트팬츠_ZA,12921890,128,3853581,23232000,100952.265625,181500.000000,0.443789
4,2021-01-03,니트 셔츠_라운드_ZB,18981424,401,3559559,28029900,47335.221945,69900.000000,0.322815
5,2021-01-03,수트_블레이져(수트)_ZB,29890941,194,7913293,38606000,154077.015464,199000.000000,0.225744
...,...,...,...,...,...,...,...,...,...
22007,2024-12-29,팬츠_팬츠(일반)_ZG,311565,5,85101,645000,62313.000000,129000.000000,0.516953
22008,2024-12-29,니트 셔츠_라운드_ZG,0,0,0,0,0.000000,0.000000,0.000000
22009,2024-12-29,점퍼_점퍼_ZG,0,0,0,0,0.000000,0.000000,0.000000
22010,2024-12-29,팬츠_반바지_ZG,0,0,0,0,0.000000,0.000000,0.000000
22011,2024-12-29,팬츠_팬츠(일반)_ZG,0,0,0,0,0.000000,0.000000,0.000000