In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import datetime

# 불필요한 경고문 생략(선택)
import warnings
warnings.filterwarnings('ignore')

# 모든 컬럼 출력설정(선택)
pd.set_option('display.max_columns', None)

df = pd.read_csv('model_df.csv')
df.isna().sum()

기획년도             0
주차               0
카테고리             0
라인               0
시즌이월             0
시즌               0
복종               0
소품종              0
성별               0
총입고수량            0
판매수량             0
판매액              0
평균택가             0
평균원가             0
총입고원가            0
총입고택가            0
매출원가계            0
판매택가계            0
주차별_평균_실판매가    300
월                0
월별_평균_실판매가      89
시즌별_평균_실판매가      0
실판매가            20
할인율             20
누적판매수량           0
누적판매액            0
누적매출원가           0
누적판매택가           0
누적판매율            0
ROI              0
맑음               0
흐림               0
비                0
강한 비             0
눈                0
강한 눈             0
진눈깨비             0
악천후일수            0
평균기온(도)          0
dtype: int64

In [2]:
condition = (df['할인율'].isna()) | (df['할인율'] < 0)
df[condition]

,기획년도,주차,카테고리,라인,시즌이월,시즌,복종,소품종,성별,총입고수량,판매수량,판매액,평균택가,평균원가,총입고원가,총입고택가,매출원가계,판매택가계,주차별_평균_실판매가,월,월별_평균_실판매가,시즌별_평균_실판매가,실판매가,할인율,누적판매수량,누적판매액,누적매출원가,누적판매택가,누적판매율,ROI,맑음,흐림,비,강한 비,눈,강한 눈,진눈깨비,악천후일수,평균기온(도)
22,2021,2021-01-10,봄_코트_싱글코트_ZB,ZB,01_시즌,봄,코트,싱글코트,1:남성,10358,-21,-7550500,249000,25439,263497162,2579142000,-534219,-5229000,359548.0,1,178906.0,119035,359548.0,-44.0,58,12095600,1465587,14442000,0.56,0.04,6,0,0,0,1,0,0,0,-2.1
44,2021,2021-01-17,봄_코트_더블코트_ZB,ZB,01_시즌,봄,코트,더블코트,1:남성,3377,-12,-5411000,329000,34815,117570255,1111033000,-417780,-3948000,450917.0,1,243505.0,144883,450917.0,-37.0,78,16465000,2715480,25662000,2.31,0.10,5,0,0,0,2,0,0,0,0.3
196,2021,2021-02-21,여름_수트_블레이져(수트)_ZC,ZC,01_시즌,여름,수트,블레이져(수트),1:남성,2906,64,14553970,219000,46217,134307571,636414000,2957909,14016000,214150.0,2,173159.0,168132,227406.0,-4.0,64,14553970,2957909,14016000,2.20,0.08,7,0,0,0,0,0,0,0,6.2
198,2021,2021-02-21,여름_수트_수트팬츠_ZC,ZC,01_시즌,여름,수트,수트팬츠,1:남성,3487,83,9949030,112333,22520,78527240,391706333,1869160,9323667,108165.0,2,82416.0,87413,119868.0,-7.0,83,9949030,1869160,9323667,2.38,0.09,7,0,0,0,0,0,0,0,6.2
201,2021,2021-02-21,여름_점퍼_점퍼_ZB,ZB,01_시즌,여름,점퍼,점퍼,1:남성,8338,212,49571200,224000,20458,170574635,1867712000,4336990,47488000,218464.0,2,189298.0,109435,233826.0,-4.0,260,59123200,5318950,58240000,3.12,0.28,7,0,0,0,0,0,0,0,6.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,2024,2024-04-07,봄_자켓_싱글재킷_ZB,ZB,01_시즌,봄,자켓,싱글재킷,1:남성,2722,0,0,299000,29549,80432378,813878000,0,0,78569.0,4,79111.0,121717,NaN,NaN,1515,151151964,44766735,452985000,55.66,1.15,6,1,0,0,0,0,0,0,16.0
8134,2024,2024-09-22,여름_점퍼_점퍼_ZB,ZB,01_시즌,여름,점퍼,점퍼,1:남성,11515,2,528000,249000,24849,286136235,2867235000,49698,498000,100209.0,9,101424.0,113074,264000.0,-6.0,8889,952115530,220882705,2213361000,77.19,2.25,5,1,1,0,0,0,0,0,22.2
8261,2024,2024-10-06,겨울_스웨터_Turtle_ZB,ZB,01_시즌,겨울,스웨터,Turtle,1:남성,21528,80,9714900,119000,15076,324563304,2561832000,1206107,9520000,119937.0,10,97449.0,68760,121436.0,-2.0,121,14637500,1874325,16039000,0.56,0.04,5,2,0,0,0,0,0,0,17.8
8270,2024,2024-10-06,겨울_코트_싱글코트_ZB,ZB,01_시즌,겨울,코트,싱글코트,1:남성,8007,5,1995000,349000,58256,466451788,2794443000,291278,1745000,399000.0,10,290806.0,189153,399000.0,-14.0,5,1995000,291278,1745000,0.06,0.00,5,2,0,0,0,0,0,0,17.8
8840,2024,2024-12-29,사계절_데님_데님팬츠_ZB,ZB,01_시즌,사계절,데님,데님팬츠,1:남성,16214,0,0,99000,15786,255959609,1605186000,0,0,43922.0,12,42004.0,49757,NaN,NaN,12415,577033401,184806171,1229085000,76.57,1.33,3,0,0,0,0,0,0,0,2.4

In [3]:
condition = (df['할인율'].isna()) | (df['할인율'] < 0)

df.loc[condition, '실판매가'] = df.loc[condition, '주차별_평균_실판매가']
df.loc[condition, '할인율'] = (1 - df.loc[condition, '실판매가'] / df.loc[condition, '평균택가']) * 100

In [4]:
condition = (df['할인율'].isna()) | (df['할인율'] < 0)
df[condition]

,기획년도,주차,카테고리,라인,시즌이월,시즌,복종,소품종,성별,총입고수량,판매수량,판매액,평균택가,평균원가,총입고원가,총입고택가,매출원가계,판매택가계,주차별_평균_실판매가,월,월별_평균_실판매가,시즌별_평균_실판매가,실판매가,할인율,누적판매수량,누적판매액,누적매출원가,누적판매택가,누적판매율,ROI,맑음,흐림,비,강한 비,눈,강한 눈,진눈깨비,악천후일수,평균기온(도)
22,2021,2021-01-10,봄_코트_싱글코트_ZB,ZB,01_시즌,봄,코트,싱글코트,1:남성,10358,-21,-7550500,249000,25439,263497162,2579142000,-534219,-5229000,359548.0,1,178906.0,119035,359548.0,-44.396787,58,12095600,1465587,14442000,0.56,0.04,6,0,0,0,1,0,0,0,-2.1
44,2021,2021-01-17,봄_코트_더블코트_ZB,ZB,01_시즌,봄,코트,더블코트,1:남성,3377,-12,-5411000,329000,34815,117570255,1111033000,-417780,-3948000,450917.0,1,243505.0,144883,450917.0,-37.056839,78,16465000,2715480,25662000,2.31,0.10,5,0,0,0,2,0,0,0,0.3
393,2021,2021-03-28,여름_스웨터_T-에리_ZB,ZB,01_시즌,여름,스웨터,T-에리,1:남성,31276,-76,-18573431,89900,8224,257229462,2811712400,-625062,-6832400,244387.0,3,151222.0,41028,244387.0,-171.843159,1050,46799119,7684818,94395000,3.36,0.14,5,1,1,0,0,0,0,0,13.6
1028,2021,2021-07-25,가을_니트 셔츠_라운드_ZB,ZB,01_시즌,가을,니트 셔츠,라운드,1:남성,10931,-7,-506220,69900,8312,90858472,764076900,-58184,-489300,72317.0,7,64118.0,31895,72317.0,-3.457797,49,2625300,407288,3425100,0.45,0.02,5,1,1,0,0,0,0,0,30.6
1045,2021,2021-08-01,여름_수트_블레이져(수트)_ZA,ZA,01_시즌,여름,수트,블레이져(수트),1:남성,9868,13,3793111,259000,46376,457634668,2555812000,602883,3367000,270022.0,8,181461.0,177289,270022.0,-4.255598,6374,1123062982,295251287,1650866000,64.59,1.59,4,1,2,0,0,0,0,0,28.0
1165,2021,2021-08-22,여름_수트_수트팬츠_ZB,ZB,01_시즌,여름,수트,수트팬츠,1:남성,12522,1,268680,99000,21371,267610166,1239678000,21371,99000,100902.0,8,85822.0,78757,100902.0,-1.921212,11122,831081767,237901007,1101078000,88.82,1.93,1,4,2,0,0,0,0,0,23.8
1221,2021,2021-08-29,사계절_우븐 셔츠_드레스셔츠_ZC,ZC,01_시즌,사계절,우븐 셔츠,드레스셔츠,1:남성,1000,2,83000,39900,7535,7535000,39900000,15070,79800,41500.0,8,29980.0,28709,41500.0,-4.010025,328,9326305,2471480,13087200,32.80,0.80,3,2,2,0,0,0,0,0,23.0
1305,2021,2021-09-12,사계절_자켓_싱글재킷_ZB,ZB,01_시즌,사계절,자켓,싱글재킷,1:남성,5145,15,3438463,199000,23618,121514610,1023855000,354270,2985000,229231.0,9,131496.0,110719,229231.0,-15.191457,3154,310353014,74491172,627646000,61.30,1.71,7,0,0,0,0,0,0,0,23.9
1338,2021,2021-09-12,겨울_사파리_패딩사파리_ZB,ZB,01_시즌,겨울,사파리,패딩사파리,1:남성,6290,-24,-13188700,399000,30461,191599690,2509710000,-731064,-9576000,492244.0,9,255224.0,217449,492244.0,-23.369424,56,11776700,1705816,22344000,0.89,0.05,7,0,0,0,0,0,0,0,23.9
1471,2021,2021-10-03,겨울_코트_싱글코트_ZA,ZA,01_시즌,겨울,코트,싱글코트,1:남성,6002,-1,-1533300,549000,73081,438632162,3295098000,-73081,-549000,1533300.0,10,541679.0,348105,1533300.0,-179.289617,48,14389700,3516218,26352000,0.80,0.02,1,3,3,0,0,0,0,0,21.0
1611,2021,2021-10-24,사계절_자켓_싱글재킷_ZB,ZB,01_시즌,사계절,자켓,싱글재킷,1:남성,5145,5,1342699,199000,23618,121514610,1023855000,118090,995000,268540.0,10,128486.0,110719,268540.0,-34.944724,3878,357539383,91590604,771722000,75.37,1.92,6,1,0,0,0,0,0,0,12.9
2082,2022,2022-01-16,사계절_팬츠_니트팬츠_ZB,ZB,01_시즌,사계절,팬츠,니트팬츠,1:남성,10228,-1,-145700,69900,7153,73160884,714937200,-7153,-69900,145700.0,1,68374.0,26418,145700.0,-108.440629,17,896200,120873,1188300,0.17,0.01,5,0,0,0,2,0,0,0,-3.7
2095,2022,2022-01-16,봄_스웨터_VEST_ZA,ZA,01_시즌,봄,스웨터,VEST,3:남녀공용,1777,-27,-2952420,99900,8436,14990772,177522300,-227772,-2697300,109349.0,1,71880.0,48657,109349.0,-9.458458,67,4016810,565212,6693300,3.77,0.21,5,0,0,0,2,0,0,0,-3.7
2104,2022,2022-01-16,봄_우븐 셔츠_캐쥬얼셔츠_ZA,ZA,01_시즌,봄,우븐 셔츠,캐쥬얼셔츠,1:남성,3710,-37,-5089460,129900,13854,51398340,481929000,-512598,-4806300,137553.0,1,96570.0,65982,137553.0,-5.891455,113,9497860,1565502,14678700,3.05,0.14,5,0,0,0,2,0,0,0,-3.7
2150,2022,2022-01-30,봄_팬츠_니트팬츠_ZA,ZA,01_시즌,봄,팬츠,니트팬츠,1:남성,5982,-3,-303480,89900,8963,53616666,537781800,-26889,-269700,101160.0,1,70370.0,44193,101160.0,-12.525028,76,3981540,681188,6832400,1.27,0.05,5,0,0,0,2,0,0,0,-3.3
2389,2022,2022-03-13,여름_자켓_싱글재킷_ZB,ZB,01_시즌,여름,자켓,싱글재킷,1:남성,8822,-2,-597000,239000,23470,207052340,2108458000,-46940,-478000,298500.0,3,211722.0,112799,298500.0,-24.895397,94,15103480,2206180,22466000,1.07,0.06,6,0,0,0,1,0,0,0,8.4
2436,2022,2022-03-20,여름_자켓_싱글재킷_ZB,ZB,01_시즌,여름,자켓,싱글재킷,1:남성,8822,-11,-2746500,239000,23470,207052340,2108458000,-258170,-2629000,249682.0,3,211722.0,112799,249682.0,-4.469456,83,12356980,1948010,19837000,0.94,0.04,7,0,0,0,0,0,0,0,8.0
3159,2022,2022-07-17,여름_수트_수트팬츠_ZC,ZC,01_시즌,여름,수트,수트팬츠,1:남성,8149,27,4495380,145667,24146,196768470,1187037667,651951,3933000,147983.0,7,117619.0,109098,147983.0,-1.589928,6199,659471099,145703672,892946001,76.07,2.31,2,2,3,0,0,0,0,0,25.7
3303,2022,2022-08-14,여름_수트_블레이져(수트)_ZC,ZC,01_시즌,여름,수트,블레이져(수트),1:남성,6792,-5,1990019,265667,49139,333749824,1804408000,-245693,-1328333,469246.0,8,216357.0,196126,469246.0,-76.629389,6155,1202526864,293285669,1618751667,90.62,2.40,1,4,1,1,0,0,0,1,26.9
3325,2022,2022-08-14,가을_우븐 셔츠_캐쥬얼셔츠_ZB,ZB,01_시즌,가을,우븐 셔츠,캐쥬얼셔츠,1:남성,17454,-4,-2614315,89900,7880,137537520,1569114600,-31520,-359600,110668.0,8,60865.0,43894,110668.0,-23.101224,159,8786379,1252920,14294100,0.91,0.05,1,4,1,1,0,0,0,1,26.9
3327,2022,2022-08-14,가을_팬츠_니트팬츠_ZB,ZB,01_시즌,가을,팬츠,니트팬츠,3:남녀공용,5416,-6,-891506,89900,10684,57864544,486898400,-64104,-539400,148584.0,8,77434.0,48288,148584.0,-65.276974,25,1338014,267100,2247500,0.46,0.02,1,4,1,1,0,0,0,1,26.9
3415,2022,2022-08-28,가을_스웨터_오픈형(CARDIGAN)_ZB,ZB,01_시즌,가을,스웨터,오픈형(CARDIGAN),1:남성,6083,20,4060950,199900,21990,133765170,1215991700,439800,3998000,203048.0,8,138395.0,119456,203048.0,-1.574787,110,13790950,2418900,21989000,1.81,0.08,4,2,1,0,0,0,0,0,22.5
3620,2022,2022-09-25,여름_스웨터_라운드_ZB,ZB,01_시즌,여름,스웨터,라운드,1:남성,31511,-3,-513100,89900,10642,335340062,2832838900,-31926,-269700,171033.0,9,64368.0,40007,171033.0,-90.248053,13625,466936150,143579403,1224887500,43.24,0.84,7,0,0,0,0,0,0,0,20.4
5439,2023,2023-07-30,사계절_니트 셔츠_라운드_ZB,ZB,01_시즌,사계절,니트 셔츠,라운드,1:남성,8765,-4,-1389760,79900,7430,65123950,700323500,-29720,-319600,347440.0,7,93621.0,37400,347440.0,-334.843554,7111,204851147,52834730,568168900,81.13,2.05,5,1,0,1,0,0,0,1,29.6
5481,2023,2023-08-06,사계절_니트 셔츠_라운드_ZB,ZB,01_시즌,사계절,니트 셔츠,라운드,1:남성,8765,15,1635000,79900,7430,65123950,700323500,111450,1198500,109000.0,8,50205.0,37400,109000.0,-36.420526,7126,206486147,52946180,569367400,81.30,2.07,2,1,4,0,0,0,0,0,26.9
5524,2023,2023-08-13,겨울_우븐 셔츠_캐쥬얼셔츠_ZA,ZA,01_시즌,겨울,우븐 셔츠,캐쥬얼셔츠,1:남성,5435,-37,-3756240,99900,10378,56404430,542956500,-383986,-3696300,101520.0,8,85176.0,71801,101520.0,-1.621622,20,1908090,207560,1998000,0.37,0.03,5,2,0,0,0,0,0,0,28.2
8261,2024,2024-10-06,겨울_스웨터_Turtle_ZB,ZB,01_시즌,겨울,스웨터,Turtle,1:남성,21528,80,9714900,119000,15076,324563304,2561832000,1206107,9520000,119937.0,10,97449.0,68760,119937.0,-0.787395,121,14637500,1874325,16039000,0.56,0.04,5,2,0,0,0,0,0,0,17.8
8270,2024,2024-10-06,겨울_코트_싱글코트_ZB,ZB,01_시즌,겨울,코트,싱글코트,1:남성,8007,5,1995000,349000,58256,466451788,2794443000,291278,1745000,399000.0,10,290806.0,189153,399000.0,-14.326648,5,1995000,291278,1745000,0.06,0.00,5,2,0,0,0,0,0,0,17.8

In [5]:
condition = (df['할인율'].isna()) | (df['할인율'] < 0)

df.loc[condition, '실판매가'] = df.loc[condition, '월별_평균_실판매가']
df.loc[condition, '할인율'] = (1 - df.loc[condition, '실판매가'] / df.loc[condition, '평균택가']) * 100

In [6]:
condition = (df['할인율'].isna()) | (df['할인율'] < 0)
df[condition]

,기획년도,주차,카테고리,라인,시즌이월,시즌,복종,소품종,성별,총입고수량,판매수량,판매액,평균택가,평균원가,총입고원가,총입고택가,매출원가계,판매택가계,주차별_평균_실판매가,월,월별_평균_실판매가,시즌별_평균_실판매가,실판매가,할인율,누적판매수량,누적판매액,누적매출원가,누적판매택가,누적판매율,ROI,맑음,흐림,비,강한 비,눈,강한 눈,진눈깨비,악천후일수,평균기온(도)
393,2021,2021-03-28,여름_스웨터_T-에리_ZB,ZB,01_시즌,여름,스웨터,T-에리,1:남성,31276,-76,-18573431,89900,8224,257229462,2811712400,-625062,-6832400,244387.0,3,151222.0,41028,151222.0,-68.211346,1050,46799119,7684818,94395000,3.36,0.14,5,1,1,0,0,0,0,0,13.6
5439,2023,2023-07-30,사계절_니트 셔츠_라운드_ZB,ZB,01_시즌,사계절,니트 셔츠,라운드,1:남성,8765,-4,-1389760,79900,7430,65123950,700323500,-29720,-319600,347440.0,7,93621.0,37400,93621.0,-17.172716,7111,204851147,52834730,568168900,81.13,2.05,5,1,0,1,0,0,0,1,29.6

In [7]:
condition = (df['할인율'].isna()) | (df['할인율'] < 0)

df.loc[condition, '실판매가'] = df.loc[condition, '시즌별_평균_실판매가']
df.loc[condition, '할인율'] = (1 - df.loc[condition, '실판매가'] / df.loc[condition, '평균택가']) * 100

In [8]:
condition = (df['할인율'].isna()) | (df['할인율'] < 0)
df[condition]

Empty DataFrame
Columns: [기획년도, 주차, 카테고리, 라인, 시즌이월, 시즌, 복종, 소품종, 성별, 총입고수량, 판매수량, 판매액, 평균택가, 평균원가, 총입고원가, 총입고택가, 매출원가계, 판매택가계, 주차별_평균_실판매가, 월, 월별_평균_실판매가, 시즌별_평균_실판매가, 실판매가, 할인율, 누적판매수량, 누적판매액, 누적매출원가, 누적판매택가, 누적판매율, ROI, 맑음, 흐림, 비, 강한 비, 눈, 강한 눈, 진눈깨비, 악천후일수, 평균기온(도)]
Index: []

In [9]:
df.to_csv("model_df_할인율NaN음수처리", index=False, encoding='utf-8-sig')