In [3]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import datetime

# 불필요한 경고문 생략(선택)
import warnings
warnings.filterwarnings('ignore')

# 모든 컬럼 출력설정(선택)
pd.set_option('display.max_columns', None)

#데이터 불러오기 
model_df = pd.read_csv('model_df.csv')
new_category = pd.read_csv('카테고리매칭.csv')

In [2]:
model_df.head()

,기획년도,주차,카테고리,라인,시즌이월,시즌,복종,소품종,성별,총입고수량,판매수량,판매액,평균택가,평균원가,총입고원가,총입고택가,매출원가계,판매택가계,주차별_평균_실판매가,월,월별_평균_실판매가,시즌별_평균_실판매가,실판매가,할인율,누적판매수량,누적판매액,누적매출원가,누적판매택가,누적판매율,ROI,맑음,흐림,비,강한 비,눈,강한 눈,진눈깨비,악천후일수,평균기온(도)
0,2021,2021-01-03,봄_가죽&FUR_가죽점퍼_ZA,ZA,01_시즌,봄,가죽&FUR,가죽점퍼,1:남성,1600,53,52297400,999000,204500,327200000,1598400000,10838500,52947000,987706.0,1,530682.0,455693,986743.0,1.0,53,52297400,10838500,52947000,3.31,0.11,4,0,0,0,3,0,0,0,-9.1
1,2021,2021-01-03,사계절_우븐 셔츠_드레스셔츠_ZC,ZC,01_시즌,사계절,우븐 셔츠,드레스셔츠,1:남성,1000,15,590520,39900,7535,7535000,39900000,113025,598500,39368.0,1,30812.0,28709,39368.0,1.0,15,590520,113025,598500,1.50,0.06,4,0,0,0,3,0,0,0,-9.1
2,2021,2021-01-03,사계절_우븐 셔츠_드레스셔츠_ZB,ZB,01_시즌,사계절,우븐 셔츠,드레스셔츠,1:남성,101915,1076,44692624,56567,7777,792558983,5764991833,8367693,60865733,45059.0,1,38629.0,32928,41536.0,27.0,1076,44692624,8367693,60865733,1.06,0.04,4,0,0,0,3,0,0,0,-9.1
3,2021,2021-01-03,사계절_수트_수트팬츠_ZB,ZB,01_시즌,사계절,수트,수트팬츠,1:남성,10099,589,40054200,99000,16044,162031722,999801000,9450112,58311000,68805.0,1,66125.0,67813,68004.0,31.0,589,40054200,9450112,58311000,5.83,0.17,4,0,0,0,3,0,0,0,-9.1
4,2021,2021-01-03,사계절_수트_블레이져(수트)_ZB,ZB,01_시즌,사계절,수트,블레이져(수트),1:남성,8419,480,58066516,199000,34632,291566808,1675381000,16623360,95520000,114810.0,1,122518.0,134016,120972.0,39.0,480,58066516,16623360,95520000,5.70,0.12,4,0,0,0,3,0,0,0,-9.1

In [36]:
agg_dict = {
    '악천후일수': 'first',
    '평균기온(도)' : 'first'
}

weather_df = model_df.groupby(['주차']).agg(agg_dict).reset_index()
weather_df.head()

           주차  악천후일수  평균기온(도)
0  2021-01-03      0     -9.1
1  2021-01-10      0     -2.1
2  2021-01-17      0      0.3
3  2021-01-24      0      1.3
4  2021-01-31      0      0.6

In [ ]:
# weather_df.to_csv("weather_df.csv", index=False, encoding="utf-8-sig")

In [4]:
new_category.head()

                카테고리  시즌  복종       소품종  라인     카테고리 재매칭
0      가을_수트_수트팬츠_ZC  가을  수트      수트팬츠  ZC  가을_가성비 수트셋업
1      가을_수트_수트팬츠_ZB  가을  수트      수트팬츠  ZB  가을_가성비 수트셋업
2  가을_수트_블레이져(수트)_ZC  가을  수트  블레이져(수트)  ZC  가을_가성비 수트셋업
3  가을_수트_블레이져(수트)_ZB  가을  수트  블레이져(수트)  ZB  가을_가성비 수트셋업
4      가을_자켓_싱글재킷_ZA  가을  자켓      싱글재킷  ZA       가을_아우터

In [5]:
model_df[model_df['카테고리'].isin(['가을_수트_수트팬츠_ZC','가을_수트_수트팬츠_ZB', '가을_수트_블레이져(수트)_ZC', '가을_수트_블레이져(수트)_ZB'])]

,기획년도,주차,카테고리,라인,시즌이월,시즌,복종,소품종,성별,총입고수량,판매수량,판매액,평균택가,평균원가,총입고원가,총입고택가,매출원가계,판매택가계,주차별_평균_실판매가,월,월별_평균_실판매가,시즌별_평균_실판매가,실판매가,할인율,누적판매수량,누적판매액,누적매출원가,누적판매택가,누적판매율,ROI,맑음,흐림,비,강한 비,눈,강한 눈,진눈깨비,악천후일수,평균기온(도)
962,2021,2021-07-11,가을_수트_블레이져(수트)_ZB,ZB,01_시즌,가을,수트,블레이져(수트),1:남성,4983,190,44645200,239000,35979,179283357,1190937000,6836010,45410000,234826.0,7,187466.0,183882,234975.0,2.0,190,44645200,6836010,45410000,3.81,0.19,4,3,0,0,0,0,0,0,28.5
963,2021,2021-07-11,가을_수트_블레이져(수트)_ZC,ZC,01_시즌,가을,수트,블레이져(수트),1:남성,1000,9,2151000,239000,37750,37750000,239000000,339750,2151000,239000.0,7,151706.0,177987,239000.0,0.0,9,2151000,339750,2151000,0.90,0.04,4,3,0,0,0,0,0,0,28.5
964,2021,2021-07-11,가을_수트_수트팬츠_ZC,ZC,01_시즌,가을,수트,수트팬츠,1:남성,1200,12,1548000,129000,19972,23966400,154800000,239664,1548000,129000.0,7,110940.0,99419,129000.0,0.0,12,1548000,239664,1548000,1.00,0.05,4,3,0,0,0,0,0,0,28.5
967,2021,2021-07-11,가을_수트_수트팬츠_ZB,ZB,01_시즌,가을,수트,수트팬츠,1:남성,5980,285,36292200,129000,18718,111933640,771420000,5334630,36765000,127392.0,7,105646.0,97928,127341.0,1.0,285,36292200,5334630,36765000,4.77,0.25,4,3,0,0,0,0,0,0,28.5
994,2021,2021-07-18,가을_수트_블레이져(수트)_ZB,ZB,01_시즌,가을,수트,블레이져(수트),1:남성,4983,224,38257745,239000,35979,179283357,1190937000,8059296,53536000,151694.0,7,187466.0,183882,170794.0,29.0,414,82902945,14895306,98946000,8.31,0.34,5,1,0,1,0,0,0,1,29.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8600,2024,2024-11-17,가을_수트_수트팬츠_ZC,ZC,01_시즌,가을,수트,수트팬츠,1:남성,2936,59,2940000,149000,25262,74169232,437464000,1490458,8791000,49831.0,11,50738.0,92859,49831.0,67.0,1999,183230852,50498738,297851000,68.09,1.56,7,0,0,0,0,0,0,0,6.3
8650,2024,2024-11-24,가을_수트_블레이져(수트)_ZB,ZB,01_시즌,가을,수트,블레이져(수트),1:남성,8406,188,20481100,279000,50594,425295966,2345274000,9511735,52452000,108870.0,11,110043.0,179845,108942.0,61.0,6712,1145011924,339551795,1872648000,79.85,1.65,4,0,0,0,0,2,1,2,3.8
8651,2024,2024-11-24,가을_수트_블레이져(수트)_ZC,ZC,01_시즌,가을,수트,블레이져(수트),1:남성,2443,51,5559000,279000,52887,129202941,681597000,2697237,14229000,109000.0,11,111188.0,184109,109000.0,61.0,1988,364319174,105139356,554652000,81.38,1.75,4,0,0,0,0,2,1,2,3.8
8652,2024,2024-11-24,가을_수트_수트팬츠_ZB,ZB,01_시즌,가을,수트,수트팬츠,1:남성,10093,221,11045000,149000,25443,256792835,1503857000,5622829,32929000,49936.0,11,50430.0,90736,49977.0,66.0,7210,603899130,183419778,1074290000,71.44,1.42,4,0,0,0,0,2,1,2,3.8
8653,2024,2024-11-24,가을_수트_수트팬츠_ZC,ZC,01_시즌,가을,수트,수트팬츠,1:남성,2936,57,2850000,149000,25262,74169232,437464000,1439934,8493000,50000.0,11,50738.0,92859,50000.0,66.0,2056,186080852,51938672,306344000,70.03,1.58,4,0,0,0,0,2,1,2,3.8

## 카테고리 재매칭 컬럼 추가

In [6]:
mapping_dict = dict(zip(new_category['카테고리'], new_category['카테고리 재매칭']))

model_df['카테고리_통합'] = model_df['카테고리'].map(mapping_dict)

model_df.head()

,기획년도,주차,카테고리,라인,시즌이월,시즌,복종,소품종,성별,총입고수량,판매수량,판매액,평균택가,평균원가,총입고원가,총입고택가,매출원가계,판매택가계,주차별_평균_실판매가,월,월별_평균_실판매가,시즌별_평균_실판매가,실판매가,할인율,누적판매수량,누적판매액,누적매출원가,누적판매택가,누적판매율,ROI,맑음,흐림,비,강한 비,눈,강한 눈,진눈깨비,악천후일수,평균기온(도),카테고리_통합
0,2021,2021-01-03,봄_가죽&FUR_가죽점퍼_ZA,ZA,01_시즌,봄,가죽&FUR,가죽점퍼,1:남성,1600,53,52297400,999000,204500,327200000,1598400000,10838500,52947000,987706.0,1,530682.0,455693,986743.0,1.0,53,52297400,10838500,52947000,3.31,0.11,4,0,0,0,3,0,0,0,-9.1,봄_아우터
1,2021,2021-01-03,사계절_우븐 셔츠_드레스셔츠_ZC,ZC,01_시즌,사계절,우븐 셔츠,드레스셔츠,1:남성,1000,15,590520,39900,7535,7535000,39900000,113025,598500,39368.0,1,30812.0,28709,39368.0,1.0,15,590520,113025,598500,1.50,0.06,4,0,0,0,3,0,0,0,-9.1,사계절_셋업셔츠
2,2021,2021-01-03,사계절_우븐 셔츠_드레스셔츠_ZB,ZB,01_시즌,사계절,우븐 셔츠,드레스셔츠,1:남성,101915,1076,44692624,56567,7777,792558983,5764991833,8367693,60865733,45059.0,1,38629.0,32928,41536.0,27.0,1076,44692624,8367693,60865733,1.06,0.04,4,0,0,0,3,0,0,0,-9.1,사계절_셋업셔츠
3,2021,2021-01-03,사계절_수트_수트팬츠_ZB,ZB,01_시즌,사계절,수트,수트팬츠,1:남성,10099,589,40054200,99000,16044,162031722,999801000,9450112,58311000,68805.0,1,66125.0,67813,68004.0,31.0,589,40054200,9450112,58311000,5.83,0.17,4,0,0,0,3,0,0,0,-9.1,사계절_가성비 수트셋업
4,2021,2021-01-03,사계절_수트_블레이져(수트)_ZB,ZB,01_시즌,사계절,수트,블레이져(수트),1:남성,8419,480,58066516,199000,34632,291566808,1675381000,16623360,95520000,114810.0,1,122518.0,134016,120972.0,39.0,480,58066516,16623360,95520000,5.70,0.12,4,0,0,0,3,0,0,0,-9.1,사계절_가성비 수트셋업

In [7]:
model_df[model_df['카테고리'].isin(['가을_수트_수트팬츠_ZC','가을_수트_수트팬츠_ZB', '가을_수트_블레이져(수트)_ZC', '가을_수트_블레이져(수트)_ZB'])]

,기획년도,주차,카테고리,라인,시즌이월,시즌,복종,소품종,성별,총입고수량,판매수량,판매액,평균택가,평균원가,총입고원가,총입고택가,매출원가계,판매택가계,주차별_평균_실판매가,월,월별_평균_실판매가,시즌별_평균_실판매가,실판매가,할인율,누적판매수량,누적판매액,누적매출원가,누적판매택가,누적판매율,ROI,맑음,흐림,비,강한 비,눈,강한 눈,진눈깨비,악천후일수,평균기온(도),카테고리_통합
962,2021,2021-07-11,가을_수트_블레이져(수트)_ZB,ZB,01_시즌,가을,수트,블레이져(수트),1:남성,4983,190,44645200,239000,35979,179283357,1190937000,6836010,45410000,234826.0,7,187466.0,183882,234975.0,2.0,190,44645200,6836010,45410000,3.81,0.19,4,3,0,0,0,0,0,0,28.5,가을_가성비 수트셋업
963,2021,2021-07-11,가을_수트_블레이져(수트)_ZC,ZC,01_시즌,가을,수트,블레이져(수트),1:남성,1000,9,2151000,239000,37750,37750000,239000000,339750,2151000,239000.0,7,151706.0,177987,239000.0,0.0,9,2151000,339750,2151000,0.90,0.04,4,3,0,0,0,0,0,0,28.5,가을_가성비 수트셋업
964,2021,2021-07-11,가을_수트_수트팬츠_ZC,ZC,01_시즌,가을,수트,수트팬츠,1:남성,1200,12,1548000,129000,19972,23966400,154800000,239664,1548000,129000.0,7,110940.0,99419,129000.0,0.0,12,1548000,239664,1548000,1.00,0.05,4,3,0,0,0,0,0,0,28.5,가을_가성비 수트셋업
967,2021,2021-07-11,가을_수트_수트팬츠_ZB,ZB,01_시즌,가을,수트,수트팬츠,1:남성,5980,285,36292200,129000,18718,111933640,771420000,5334630,36765000,127392.0,7,105646.0,97928,127341.0,1.0,285,36292200,5334630,36765000,4.77,0.25,4,3,0,0,0,0,0,0,28.5,가을_가성비 수트셋업
994,2021,2021-07-18,가을_수트_블레이져(수트)_ZB,ZB,01_시즌,가을,수트,블레이져(수트),1:남성,4983,224,38257745,239000,35979,179283357,1190937000,8059296,53536000,151694.0,7,187466.0,183882,170794.0,29.0,414,82902945,14895306,98946000,8.31,0.34,5,1,0,1,0,0,0,1,29.8,가을_가성비 수트셋업
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8600,2024,2024-11-17,가을_수트_수트팬츠_ZC,ZC,01_시즌,가을,수트,수트팬츠,1:남성,2936,59,2940000,149000,25262,74169232,437464000,1490458,8791000,49831.0,11,50738.0,92859,49831.0,67.0,1999,183230852,50498738,297851000,68.09,1.56,7,0,0,0,0,0,0,0,6.3,가을_가성비 수트셋업
8650,2024,2024-11-24,가을_수트_블레이져(수트)_ZB,ZB,01_시즌,가을,수트,블레이져(수트),1:남성,8406,188,20481100,279000,50594,425295966,2345274000,9511735,52452000,108870.0,11,110043.0,179845,108942.0,61.0,6712,1145011924,339551795,1872648000,79.85,1.65,4,0,0,0,0,2,1,2,3.8,가을_가성비 수트셋업
8651,2024,2024-11-24,가을_수트_블레이져(수트)_ZC,ZC,01_시즌,가을,수트,블레이져(수트),1:남성,2443,51,5559000,279000,52887,129202941,681597000,2697237,14229000,109000.0,11,111188.0,184109,109000.0,61.0,1988,364319174,105139356,554652000,81.38,1.75,4,0,0,0,0,2,1,2,3.8,가을_가성비 수트셋업
8652,2024,2024-11-24,가을_수트_수트팬츠_ZB,ZB,01_시즌,가을,수트,수트팬츠,1:남성,10093,221,11045000,149000,25443,256792835,1503857000,5622829,32929000,49936.0,11,50430.0,90736,49977.0,66.0,7210,603899130,183419778,1074290000,71.44,1.42,4,0,0,0,0,2,1,2,3.8,가을_가성비 수트셋업
8653,2024,2024-11-24,가을_수트_수트팬츠_ZC,ZC,01_시즌,가을,수트,수트팬츠,1:남성,2936,57,2850000,149000,25262,74169232,437464000,1439934,8493000,50000.0,11,50738.0,92859,50000.0,66.0,2056,186080852,51938672,306344000,70.03,1.58,4,0,0,0,0,2,1,2,3.8,가을_가성비 수트셋업

In [10]:
model_df['실판매가'].isna().sum()

20

In [11]:
model_df[model_df['실판매가'].isna()]

,기획년도,주차,카테고리,라인,시즌이월,시즌,복종,소품종,성별,총입고수량,판매수량,판매액,평균택가,평균원가,총입고원가,총입고택가,매출원가계,판매택가계,주차별_평균_실판매가,월,월별_평균_실판매가,시즌별_평균_실판매가,실판매가,할인율,누적판매수량,누적판매액,누적매출원가,누적판매택가,누적판매율,ROI,맑음,흐림,비,강한 비,눈,강한 눈,진눈깨비,악천후일수,평균기온(도),카테고리_통합
3191,2022,2022-07-24,여름_자켓_싱글재킷_ZB,ZB,01_시즌,여름,자켓,싱글재킷,1:남성,10843,0,0,239000,23694,256914042,2591477000,0,0,86720.0,7,68084.0,112799,NaN,NaN,5033,493741815,119198386,1202887000,46.42,1.28,5,1,1,0,0,0,0,0,28.9,여름_자켓
3255,2022,2022-07-31,여름_니트 셔츠_라운드_ZB,ZB,01_시즌,여름,니트 셔츠,라운드,3:남녀공용,404349,0,0,61329,7142,2887687266,24798146529,0,0,24381.0,7,18355.0,20077,NaN,NaN,160076,2823849836,1135444298,9799267171,39.59,0.50,0,2,3,2,0,0,0,2,28.1,여름_반팔티셔츠
3268,2022,2022-08-07,여름_자켓_싱글재킷_ZB,ZB,01_시즌,여름,자켓,싱글재킷,1:남성,10843,0,0,239000,23694,256914042,2591477000,0,0,78004.0,8,77832.0,112799,NaN,NaN,5712,544781566,135286612,1365168000,52.68,1.40,1,1,2,3,0,0,0,3,26.2,여름_자켓
3598,2022,2022-09-18,겨울_스웨터_라운드_ZB,ZB,01_시즌,겨울,스웨터,라운드,1:남성,30849,0,0,99900,12240,377591760,3081815100,0,0,64250.0,9,55795.0,44470,NaN,NaN,1420,82862680,17380800,141858000,4.60,0.15,6,0,1,0,0,0,0,0,21.0,겨울_스웨터
3607,2022,2022-09-25,여름_니트 셔츠_라운드_ZB,ZB,01_시즌,여름,니트 셔츠,라운드,3:남녀공용,404349,0,0,61329,7143,2888149379,24798146529,0,0,15131.0,9,17635.0,20077,NaN,NaN,206978,3435260809,1470453649,12675702475,51.19,0.57,7,0,0,0,0,0,0,0,20.4,여름_반팔티셔츠
4122,2022,2022-12-11,사계절_우븐 셔츠_드레스셔츠_ZB,ZB,01_시즌,사계절,우븐 셔츠,드레스셔츠,1:남성,101890,0,0,69900,7104,723826560,7122111000,0,0,27562.0,12,26876.0,29098,NaN,NaN,60858,1951652438,441849523,4253974200,59.73,1.84,4,0,0,0,3,0,0,0,-3.2,사계절_셋업셔츠
5317,2023,2023-07-09,사계절_니트 셔츠_라운드_ZB,ZB,01_시즌,사계절,니트 셔츠,라운드,1:남성,8765,0,0,79900,7430,65123950,700323500,0,0,29000.0,7,93621.0,37400,NaN,NaN,7115,206240907,52864450,568488500,81.18,2.07,0,2,1,4,0,0,0,4,24.9,사계절_니트셋업
5357,2023,2023-07-16,사계절_니트 셔츠_라운드_ZB,ZB,01_시즌,사계절,니트 셔츠,라운드,1:남성,8765,0,0,79900,7430,65123950,700323500,0,0,33421.0,7,93621.0,37400,NaN,NaN,7115,206240907,52864450,568488500,81.18,2.07,3,1,3,0,0,0,0,0,26.8,사계절_니트셋업
5399,2023,2023-07-23,사계절_니트 셔츠_라운드_ZB,ZB,01_시즌,사계절,니트 셔츠,라운드,1:남성,8765,0,0,79900,7430,65123950,700323500,0,0,29275.0,7,93621.0,37400,NaN,NaN,7115,206240907,52864450,568488500,81.18,2.07,2,3,2,0,0,0,0,0,27.8,사계절_니트셋업
5579,2023,2023-08-20,사계절_니트 셔츠_라운드_ZB,ZB,01_시즌,사계절,니트 셔츠,라운드,1:남성,8765,0,0,79900,7430,65123950,700323500,0,0,34817.0,8,50205.0,37400,NaN,NaN,7146,207064247,53094780,570965400,81.53,2.08,1,3,1,2,0,0,0,2,26.9,사계절_니트셋업
5743,2023,2023-09-10,사계절_데님_데님팬츠_ZB,ZB,01_시즌,사계절,데님,데님팬츠,1:남성,19971,0,0,101900,17672,352923518,2035044900,0,0,67867.0,9,67467.0,64064,NaN,NaN,7593,487776035,137229283,781588034,38.02,0.87,4,1,1,1,0,0,0,1,24.1,사계절_데님셋업
5847,2023,2023-09-24,사계절_니트 셔츠_라운드_ZB,ZB,01_시즌,사계절,니트 셔츠,라운드,1:남성,8765,0,0,79900,7430,65123950,700323500,0,0,29000.0,9,29044.0,37400,NaN,NaN,7437,214883643,55256910,594216300,84.85,2.15,3,1,3,0,0,0,0,0,21.2,사계절_니트셋업
5955,2023,2023-10-08,사계절_데님_데님팬츠_ZB,ZB,01_시즌,사계절,데님,데님팬츠,1:남성,19971,0,0,101900,17672,352923518,2035044900,0,0,62667.0,10,61683.0,64064,NaN,NaN,9155,599868110,164832550,940755834,45.84,1.08,4,2,1,0,0,0,0,0,17.0,사계절_데님셋업
6007,2023,2023-10-15,사계절_데님_데님팬츠_ZB,ZB,01_시즌,사계절,데님,데님팬츠,1:남성,19971,0,0,101900,17672,352923518,2035044900,0,0,66918.0,10,61683.0,64064,NaN,NaN,9155,599868110,164832550,940755834,45.84,1.08,5,0,2,0,0,0,0,0,14.2,사계절_데님셋업
6102,2023,2023-10-29,사계절_니트 셔츠_라운드_ZB,ZB,01_시즌,사계절,니트 셔츠,라운드,1:남성,8765,0,0,79900,7430,65123950,700323500,0,0,29672.0,10,27129.0,37400,NaN,NaN,7919,227713482,58838170,632728100,90.35,2.28,7,0,0,0,0,0,0,0,17.6,사계절_니트셋업
6104,2023,2023-10-29,사계절_데님_데님팬츠_ZB,ZB,01_시즌,사계절,데님,데님팬츠,1:남성,19971,0,0,101900,17672,352923518,2035044900,0,0,58092.0,10,61683.0,64064,NaN,NaN,9015,591497370,162358470,926489834,45.14,1.06,7,0,0,0,0,0,0,0,17.6,사계절_데님셋업
6378,2023,2023-12-10,사계절_니트 셔츠_라운드_ZB,ZB,01_시즌,사계절,니트 셔츠,라운드,1:남성,8765,0,0,79900,7430,65123950,700323500,0,0,29000.0,12,29079.0,37400,NaN,NaN,7939,227110364,58986770,634326100,90.58,2.26,6,0,0,0,1,0,0,0,5.8,사계절_니트셋업
6381,2023,2023-12-10,사계절_데님_데님팬츠_ZB,ZB,01_시즌,사계절,데님,데님팬츠,1:남성,19971,0,0,101900,17672,352923518,2035044900,0,0,51916.0,12,56001.0,64064,NaN,NaN,9789,629246680,176036442,1005360434,49.02,1.12,6,0,0,0,1,0,0,0,5.8,사계절_데님셋업
6995,2024,2024-04-07,봄_자켓_싱글재킷_ZB,ZB,01_시즌,봄,자켓,싱글재킷,1:남성,2722,0,0,299000,29549,80432378,813878000,0,0,78569.0,4,79111.0,121717,NaN,NaN,1515,151151964,44766735,452985000,55.66,1.15,6,1,0,0,0,0,0,0,16.0,봄_아우터
8840,2024,2024-12-29,사계절_데님_데님팬츠_ZB,ZB,01_시즌,사계절,데님,데님팬츠,1:남성,16214,0,0,99000,15786,255959609,1605186000,0,0,43922.0,12,42004.0,49757,NaN,NaN,12415,577033401,184806171,1229085000,76.57,1.33,3,0,0,0,0,0,0,0,2.4,사계절_데님셋업

## [기획년도, 주차, 카테고리_통합] 집계

In [ ]:
agg_dict = {
    '시즌이월': 'first', 
    '시즌': 'first', 
    '총입고수량': 'sum',
    '판매수량' : 'sum', 
    '판매액': 'sum', 
    '평균택가': 'mean', 
    '평균원가': 'mean',
    '주차별_평균_실판매가': 'mean',
    '월별_평균_실판매가': 'mean',
    '시즌별_평균_실판매가': 'mean'
}

grouped_df = model_df.groupby(['기획년도', '주차', '카테고리_통합']).agg(agg_dict).reset_index()
grouped_df.head()

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가
0,2021,2021-01-03,봄_가디건,8976,127,14957130,159900.00,14254.0,108352.00,152746.0,79061.0
1,2021,2021-01-03,봄_가성비 수트셋업,24728,498,56952161,165666.75,32867.5,135805.25,118744.0,97673.0
2,2021,2021-01-03,봄_고가 수트셋업,9635,237,32607290,265666.50,44135.5,162745.50,146321.5,116111.5
3,2021,2021-01-03,봄_맨투맨셋업,20076,401,18981424,69900.00,8878.0,47335.00,41774.0,27610.0
4,2021,2021-01-03,봄_셋업셔츠,24771,190,11160429,69900.00,6976.5,60467.00,39287.5,29786.0

In [15]:
grouped_df.isna().sum()

기획년도             0
주차               0
카테고리_통합          0
총입고수량            0
판매수량             0
판매액              0
평균택가             0
평균원가             0
주차별_평균_실판매가    114
월별_평균_실판매가      38
시즌별_평균_실판매가      0
dtype: int64

In [16]:
columns_to_round = ['평균택가','평균원가', '주차별_평균_실판매가', '월별_평균_실판매가', '시즌별_평균_실판매가']

grouped_df[columns_to_round] = grouped_df[columns_to_round].round(0)
grouped_df.head()

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가
0,2021,2021-01-03,봄_가디건,8976,127,14957130,159900.0,14254.0,108352.0,152746.0,79061.0
1,2021,2021-01-03,봄_가성비 수트셋업,24728,498,56952161,165667.0,32868.0,135805.0,118744.0,97673.0
2,2021,2021-01-03,봄_고가 수트셋업,9635,237,32607290,265666.0,44136.0,162746.0,146322.0,116112.0
3,2021,2021-01-03,봄_맨투맨셋업,20076,401,18981424,69900.0,8878.0,47335.0,41774.0,27610.0
4,2021,2021-01-03,봄_셋업셔츠,24771,190,11160429,69900.0,6976.0,60467.0,39288.0,29786.0

In [17]:
grouped_df['총입고원가'] = grouped_df['총입고수량'] * grouped_df['평균원가']
grouped_df['총입고택가'] = grouped_df['총입고수량'] * grouped_df['평균택가']
grouped_df['매출원가계'] = grouped_df['판매수량'] * grouped_df['평균원가']
grouped_df['판매택가계'] = grouped_df['판매수량'] * grouped_df['평균택가']
grouped_df

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계
0,2021,2021-01-03,봄_가디건,8976,127,14957130,159900.0,14254.0,108352.0,152746.0,79061.0,1.279439e+08,1.435262e+09,1810258.0,2.030730e+07
1,2021,2021-01-03,봄_가성비 수트셋업,24728,498,56952161,165667.0,32868.0,135805.0,118744.0,97673.0,8.127599e+08,4.096614e+09,16368264.0,8.250217e+07
2,2021,2021-01-03,봄_고가 수트셋업,9635,237,32607290,265666.0,44136.0,162746.0,146322.0,116112.0,4.252504e+08,2.559692e+09,10460232.0,6.296284e+07
3,2021,2021-01-03,봄_맨투맨셋업,20076,401,18981424,69900.0,8878.0,47335.0,41774.0,27610.0,1.782347e+08,1.403312e+09,3560078.0,2.802990e+07
4,2021,2021-01-03,봄_셋업셔츠,24771,190,11160429,69900.0,6976.0,60467.0,39288.0,29786.0,1.728025e+08,1.731493e+09,1325440.0,1.328100e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4091,2024,2024-12-29,겨울_해비스웨터,35272,1558,91596010,132333.0,17518.0,60866.0,62536.0,79178.0,6.178949e+08,4.667650e+09,27293044.0,2.061748e+08
4092,2024,2024-12-29,겨울_해비아우터,49747,3439,392281108,301500.0,39010.0,94782.0,101770.0,142052.0,1.940630e+09,1.499872e+10,134155390.0,1.036858e+09
4093,2024,2024-12-29,사계절_가성비 수트셋업,63577,405,37045998,199000.0,32310.0,93050.0,95044.0,106885.0,2.054173e+09,1.265182e+10,13085550.0,8.059500e+07
4094,2024,2024-12-29,사계절_데님셋업,23145,34,2886000,127334.0,17336.0,69794.0,64035.0,66851.0,4.012417e+08,2.947145e+09,589424.0,4.329356e+06
4095,2024,2024-12-29,사계절_셋업셔츠,194536,1499,49167250,79000.0,7624.0,34440.0,31287.0,33114.0,1.483142e+09,1.536834e+10,11428376.0,1.184210e+08

In [18]:
columns_to_round = ['평균택가','평균원가', '총입고원가', '총입고택가', '매출원가계', '판매택가계']

grouped_df[columns_to_round] = grouped_df[columns_to_round].round(0).astype('int64')
grouped_df.head()

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계
0,2021,2021-01-03,봄_가디건,8976,127,14957130,159900,14254,108352.0,152746.0,79061.0,127943904,1435262400,1810258,20307300
1,2021,2021-01-03,봄_가성비 수트셋업,24728,498,56952161,165667,32868,135805.0,118744.0,97673.0,812759904,4096613576,16368264,82502166
2,2021,2021-01-03,봄_고가 수트셋업,9635,237,32607290,265666,44136,162746.0,146322.0,116112.0,425250360,2559691910,10460232,62962842
3,2021,2021-01-03,봄_맨투맨셋업,20076,401,18981424,69900,8878,47335.0,41774.0,27610.0,178234728,1403312400,3560078,28029900
4,2021,2021-01-03,봄_셋업셔츠,24771,190,11160429,69900,6976,60467.0,39288.0,29786.0,172802496,1731492900,1325440,13281000

In [19]:
grouped_df['실판매가'] = grouped_df['판매액'] / grouped_df['판매수량']
grouped_df.head()

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계,실판매가
0,2021,2021-01-03,봄_가디건,8976,127,14957130,159900,14254,108352.0,152746.0,79061.0,127943904,1435262400,1810258,20307300,117772.677165
1,2021,2021-01-03,봄_가성비 수트셋업,24728,498,56952161,165667,32868,135805.0,118744.0,97673.0,812759904,4096613576,16368264,82502166,114361.769076
2,2021,2021-01-03,봄_고가 수트셋업,9635,237,32607290,265666,44136,162746.0,146322.0,116112.0,425250360,2559691910,10460232,62962842,137583.502110
3,2021,2021-01-03,봄_맨투맨셋업,20076,401,18981424,69900,8878,47335.0,41774.0,27610.0,178234728,1403312400,3560078,28029900,47335.221945
4,2021,2021-01-03,봄_셋업셔츠,24771,190,11160429,69900,6976,60467.0,39288.0,29786.0,172802496,1731492900,1325440,13281000,58739.100000

In [20]:
grouped_df['실판매가'].apply(np.isinf).sum()

1

In [21]:
grouped_df['실판매가'].replace([np.inf, -np.inf], np.nan, inplace=True)
grouped_df['실판매가'].apply(np.isinf).sum()

0

In [22]:
grouped_df['실판매가'].isna().sum()

120

In [23]:
grouped_df[grouped_df['실판매가'] <=0]

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계,실판매가
110,2021,2021-02-21,여름_캐주얼셔츠,42909,95,-110210,69900,6329,NaN,50254.0,24611.0,271571061,2999339100,601255,6640500,-1160.105263
337,2021,2021-05-09,여름_반바지,15800,7,-185152,54900,6646,NaN,36940.0,26361.0,105006800,867420000,46522,384300,-26450.285714
403,2021,2021-05-30,여름_반바지,31009,96,-2228828,54900,6616,49592.0,36940.0,26361.0,205155544,1702394100,635136,5270400,-23216.958333
529,2021,2021-07-25,사계절_셋업,61100,49,-4690759,138200,17391,81297.0,83182.0,76338.0,1062590100,8444020000,852159,6771800,-95729.775510
697,2021,2021-09-12,겨울_팬츠,3248,2,-595935,139000,3853,NaN,106202.0,65190.0,12514544,451472000,7706,278000,-297967.500000
1575,2022,2022-07-31,사계절_셋업,87696,23,-270806,169450,20672,48880.0,94002.0,91106.0,1812851712,14860087200,475456,3897350,-11774.173913
1607,2022,2022-08-07,여름_팬츠,215591,1315,-16560408,84900,8628,24470.0,24313.0,30018.0,1860119148,18303675900,11345820,111643500,-12593.466160
1639,2022,2022-08-21,사계절_데님셋업,27469,59,-439720,99900,12950,71836.0,58780.0,49011.0,355723550,2744153100,764050,5894100,-7452.881356
1696,2022,2022-09-04,여름_디자인팬츠,49379,26,-568069,134112,14529,54333.0,51401.0,59743.0,717427491,6622316448,377754,3486912,-21848.807692
2772,2023,2023-09-10,사계절_니트셋업,8765,9,-161800,79900,7430,NaN,29044.0,37400.0,65123950,700323500,66870,719100,-17977.777778
3412,2024,2024-05-12,봄_맨투맨셋업,8906,8,-184500,89000,6766,44988.0,32096.0,39283.0,60257996,792634000,54128,712000,-23062.500000
3413,2024,2024-05-12,봄_스웨터,22480,1,-375250,99000,15571,37873.0,32563.0,44521.0,350036080,2225520000,15571,99000,-375250.000000

In [24]:
grouped_df['실판매가'] = grouped_df['실판매가'].mask((grouped_df['실판매가'] <= 0) | (grouped_df['실판매가'].isna()), grouped_df['주차별_평균_실판매가'])

grouped_df['실판매가'] = grouped_df['실판매가'].fillna(grouped_df['월별_평균_실판매가'])

grouped_df['실판매가'] = grouped_df['실판매가'].fillna(grouped_df['시즌별_평균_실판매가'])

grouped_df.head()

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계,실판매가
0,2021,2021-01-03,봄_가디건,8976,127,14957130,159900,14254,108352.0,152746.0,79061.0,127943904,1435262400,1810258,20307300,117772.677165
1,2021,2021-01-03,봄_가성비 수트셋업,24728,498,56952161,165667,32868,135805.0,118744.0,97673.0,812759904,4096613576,16368264,82502166,114361.769076
2,2021,2021-01-03,봄_고가 수트셋업,9635,237,32607290,265666,44136,162746.0,146322.0,116112.0,425250360,2559691910,10460232,62962842,137583.502110
3,2021,2021-01-03,봄_맨투맨셋업,20076,401,18981424,69900,8878,47335.0,41774.0,27610.0,178234728,1403312400,3560078,28029900,47335.221945
4,2021,2021-01-03,봄_셋업셔츠,24771,190,11160429,69900,6976,60467.0,39288.0,29786.0,172802496,1731492900,1325440,13281000,58739.100000

In [25]:
grouped_df[grouped_df['실판매가'] <= 0]

Empty DataFrame
Columns: [기획년도, 주차, 카테고리_통합, 총입고수량, 판매수량, 판매액, 평균택가, 평균원가, 주차별_평균_실판매가, 월별_평균_실판매가, 시즌별_평균_실판매가, 총입고원가, 총입고택가, 매출원가계, 판매택가계, 실판매가]
Index: []

In [26]:
grouped_df[grouped_df['실판매가'].isna()]

Empty DataFrame
Columns: [기획년도, 주차, 카테고리_통합, 총입고수량, 판매수량, 판매액, 평균택가, 평균원가, 주차별_평균_실판매가, 월별_평균_실판매가, 시즌별_평균_실판매가, 총입고원가, 총입고택가, 매출원가계, 판매택가계, 실판매가]
Index: []

In [27]:
grouped_df['할인율'] = ((grouped_df['평균택가'] - grouped_df['실판매가']) / grouped_df['평균택가']) * 100
grouped_df.head()

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계,실판매가,할인율
0,2021,2021-01-03,봄_가디건,8976,127,14957130,159900,14254,108352.0,152746.0,79061.0,127943904,1435262400,1810258,20307300,117772.677165,26.346043
1,2021,2021-01-03,봄_가성비 수트셋업,24728,498,56952161,165667,32868,135805.0,118744.0,97673.0,812759904,4096613576,16368264,82502166,114361.769076,30.968890
2,2021,2021-01-03,봄_고가 수트셋업,9635,237,32607290,265666,44136,162746.0,146322.0,116112.0,425250360,2559691910,10460232,62962842,137583.502110,48.211852
3,2021,2021-01-03,봄_맨투맨셋업,20076,401,18981424,69900,8878,47335.0,41774.0,27610.0,178234728,1403312400,3560078,28029900,47335.221945,32.281514
4,2021,2021-01-03,봄_셋업셔츠,24771,190,11160429,69900,6976,60467.0,39288.0,29786.0,172802496,1731492900,1325440,13281000,58739.100000,15.966953

In [28]:
columns_to_round = ['실판매가', '할인율']

grouped_df[columns_to_round] = grouped_df[columns_to_round].round(0).astype('int64')
grouped_df.head()

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계,실판매가,할인율
0,2021,2021-01-03,봄_가디건,8976,127,14957130,159900,14254,108352.0,152746.0,79061.0,127943904,1435262400,1810258,20307300,117773,26
1,2021,2021-01-03,봄_가성비 수트셋업,24728,498,56952161,165667,32868,135805.0,118744.0,97673.0,812759904,4096613576,16368264,82502166,114362,31
2,2021,2021-01-03,봄_고가 수트셋업,9635,237,32607290,265666,44136,162746.0,146322.0,116112.0,425250360,2559691910,10460232,62962842,137584,48
3,2021,2021-01-03,봄_맨투맨셋업,20076,401,18981424,69900,8878,47335.0,41774.0,27610.0,178234728,1403312400,3560078,28029900,47335,32
4,2021,2021-01-03,봄_셋업셔츠,24771,190,11160429,69900,6976,60467.0,39288.0,29786.0,172802496,1731492900,1325440,13281000,58739,16

In [30]:
grouped_df.dtypes

기획년도             int64
주차              object
카테고리_통합         object
총입고수량            int64
판매수량             int64
판매액              int64
평균택가             int64
평균원가             int64
주차별_평균_실판매가    float64
월별_평균_실판매가     float64
시즌별_평균_실판매가    float64
총입고원가            int64
총입고택가            int64
매출원가계            int64
판매택가계            int64
실판매가             int64
할인율              int64
dtype: object

In [31]:
grouped_df[grouped_df['할인율'] < 0]

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계,실판매가,할인율
109,2021,2021-02-21,여름_점퍼,8338,212,49571200,224000,20458,218464.0,189298.0,109435.0,170578804,1867712000,4337096,47488000,233826,-4
523,2021,2021-07-25,가을_이너,10931,-7,-506220,69900,8312,72317.0,64118.0,31895.0,90858472,764076900,-58184,-489300,72317,-3
676,2021,2021-09-05,여름_고가 수트셋업,21688,120,25641766,199000,34696,122528.0,130567.0,135248.0,752486848,4315912000,4163520,23880000,213681,-7
698,2021,2021-09-12,겨울_해비스웨터,21384,-19,-3486469,169900,16866,104876.0,112011.0,84261.0,360662544,3633141600,-320454,-3228100,183498,-8
736,2021,2021-09-19,여름_고가 수트셋업,21688,-61,-14925700,199000,34696,139832.0,130567.0,135248.0,752486848,4315912000,-2116456,-12139000,244684,-23
1050,2022,2022-01-16,봄_캐주얼셔츠,3710,-37,-5089460,129900,13854,137553.0,96570.0,65982.0,51398340,481929000,-512598,-4806300,137553,-6
1611,2022,2022-08-14,가을_캐주얼셔츠,17454,-4,-2614315,89900,7880,110668.0,60865.0,43894.0,137537520,1569114600,-31520,-359600,653579,-627
1612,2022,2022-08-14,가을_팬츠,5416,-6,-891506,89900,10684,148584.0,77434.0,48288.0,57864544,486898400,-64104,-539400,148584,-65
1654,2022,2022-08-28,가을_이너,15894,15,3676642,144900,17444,139955.0,98130.0,80166.0,277254936,2303040600,261660,2173500,245109,-69
1670,2022,2022-08-28,여름_반바지,45666,-7,-4118710,79900,8726,26396.0,22478.0,26288.0,398481516,3648713400,-61082,-559300,588387,-636
2621,2023,2023-07-30,사계절_니트셋업,8765,-4,-1389760,79900,7430,347440.0,93621.0,37400.0,65123950,700323500,-29720,-319600,347440,-335
2641,2023,2023-08-06,사계절_니트셋업,8765,15,1635000,79900,7430,109000.0,50205.0,37400.0,65123950,700323500,111450,1198500,109000,-36
2661,2023,2023-08-13,겨울_아우터셔츠,5435,-37,-3756240,99900,10378,101520.0,85176.0,71801.0,56404430,542956500,-383986,-3696300,101520,-2
2750,2023,2023-09-03,여름_디자인팬츠,35860,50,12234437,139000,16327,56294.0,56514.0,73028.0,585486220,4984540000,816350,6950000,244689,-76
2754,2023,2023-09-03,여름_자켓,30109,92,28738328,295667,38690,133572.0,133686.0,159446.0,1164917210,8902237703,3559480,27201364,312373,-6
2803,2023,2023-09-17,사계절_데님셋업,26147,-36,-6872200,130450,16326,92215.0,89400.0,81688.0,426875922,3410876150,-587736,-4696200,190894,-46
2903,2023,2023-10-15,사계절_데님셋업,26147,55,7464619,130450,16326,95732.0,88804.0,81688.0,426875922,3410876150,897930,7174750,135720,-4
3039,2023,2023-12-03,사계절_데님셋업,26147,11,1479582,130450,16326,71166.0,69254.0,81688.0,426875922,3410876150,179586,1434950,134507,-3
3071,2023,2023-12-17,사계절_데님셋업,26147,-12,-2187981,130450,16326,73418.0,69254.0,81688.0,426875922,3410876150,-195912,-1565400,182332,-40

In [33]:
grouped_df[(grouped_df['카테고리_통합'] == '사계절_데님셋업')&(grouped_df['기획년도']==2023)]

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계,실판매가,할인율
2051,2023,2023-01-01,사계절_데님셋업,2874,17,1463627,159000,13742,86096.0,92154.0,99312.0,39494508,456966000,233614,2703000,86096,46
2064,2023,2023-01-08,사계절_데님셋업,2874,26,2378000,159000,13742,91462.0,92154.0,99312.0,39494508,456966000,357292,4134000,91462,42
2080,2023,2023-01-15,사계절_데님셋업,15874,121,8740100,131116,15964,80190.0,79465.0,81688.0,253412536,2081335384,1931644,15865036,72232,45
2096,2023,2023-01-22,사계절_데님셋업,15874,96,7243810,131116,15964,80774.0,79465.0,81688.0,253412536,2081335384,1532544,12587136,75456,42
2112,2023,2023-01-29,사계절_데님셋업,15874,174,12546121,131116,15964,80806.0,79465.0,81688.0,253412536,2081335384,2777736,22814184,72104,45
2128,2023,2023-02-05,사계절_데님셋업,15874,145,10586254,131116,15966,80083.0,82609.0,81688.0,253444284,2081335384,2315070,19011820,73009,44
2145,2023,2023-02-12,사계절_데님셋업,15874,212,15734000,131116,15966,82628.0,82609.0,81688.0,253444284,2081335384,3384792,27796592,74217,43
2163,2023,2023-02-19,사계절_데님셋업,15874,270,19501900,131116,15966,84036.0,82609.0,81688.0,253444284,2081335384,4310820,35401320,72229,45
2182,2023,2023-02-26,사계절_데님셋업,15874,239,17976150,131116,15966,83687.0,82609.0,81688.0,253444284,2081335384,3815874,31336724,75214,43
2201,2023,2023-03-05,사계절_데님셋업,15874,426,31566804,131116,15966,81798.0,82272.0,81688.0,253444284,2081335384,6801516,55855416,74100,43
2221,2023,2023-03-12,사계절_데님셋업,15874,334,24619675,131116,15966,82968.0,82272.0,81688.0,253444284,2081335384,5332644,43792744,73712,44
2243,2023,2023-03-19,사계절_데님셋업,15874,359,26852700,131116,15966,82704.0,82272.0,81688.0,253444284,2081335384,5731794,47070644,74799,43
2265,2023,2023-03-26,사계절_데님셋업,15874,387,28626095,131116,15966,81618.0,82272.0,81688.0,253444284,2081335384,6178842,50741892,73969,44
2288,2023,2023-04-02,사계절_데님셋업,15874,395,28996153,131116,15966,82023.0,83028.0,81688.0,253444284,2081335384,6306570,51790820,73408,44
2311,2023,2023-04-09,사계절_데님셋업,15874,345,25245040,131116,15966,83514.0,83028.0,81688.0,253444284,2081335384,5508270,45235020,73174,44
2334,2023,2023-04-16,사계절_데님셋업,15874,284,20679735,131116,15966,86239.0,83028.0,81688.0,253444284,2081335384,4534344,37236944,72816,44
2357,2023,2023-04-23,사계절_데님셋업,15874,270,18890330,131116,15966,82362.0,83028.0,81688.0,253444284,2081335384,4310820,35401320,69964,47
2380,2023,2023-04-30,사계절_데님셋업,15874,258,17944765,131116,15966,80998.0,83028.0,81688.0,253444284,2081335384,4119228,33827928,69553,47
2403,2023,2023-05-07,사계절_데님셋업,15874,368,23798843,131116,15966,80850.0,77552.0,81688.0,253444284,2081335384,5875488,48250688,64671,51
2426,2023,2023-05-14,사계절_데님셋업,15874,284,17825040,131116,15966,76680.0,77552.0,81688.0,253444284,2081335384,4534344,37236944,62764,52
2449,2023,2023-05-21,사계절_데님셋업,15874,249,15634445,131116,15966,79820.0,77552.0,81688.0,253444284,2081335384,3975534,32647884,62789,52
2472,2023,2023-05-28,사계절_데님셋업,15874,188,12322250,131116,15966,72860.0,77552.0,81688.0,253444284,2081335384,3001608,24649808,65544,50
2487,2023,2023-06-04,사계절_데님셋업,15874,285,15683956,131116,15966,68390.0,74275.0,81688.0,253444284,2081335384,4550310,37368060,55031,58
2502,2023,2023-06-11,사계절_데님셋업,15874,253,13591700,131116,15966,74142.0,74275.0,81688.0,253444284,2081335384,4039398,33172348,53722,59
2517,2023,2023-06-18,사계절_데님셋업,15874,184,9658900,131116,15966,75316.0,74275.0,81688.0,253444284,2081335384,2937744,24125344,52494,60
2532,2023,2023-06-25,사계절_데님셋업,15874,156,9165800,131116,15966,79251.0,74275.0,81688.0,253444284,2081335384,2490696,20454096,58755,55
2547,2023,2023-07-02,사계절_데님셋업,15874,138,8768698,131116,15966,59700.0,72300.0,81688.0,253444284,2081335384,2203308,18094008,63541,52
2565,2023,2023-07-09,사계절_데님셋업,15874,146,9005680,131116,15966,54842.0,72300.0,81688.0,253444284,2081335384,2331036,19142936,61683,53
2584,2023,2023-07-16,사계절_데님셋업,15874,126,7648240,131116,15966,81686.0,72300.0,81688.0,253444284,2081335384,2011716,16520616,60700,54
2603,2023,2023-07-23,사계절_데님셋업,15874,121,6963910,131116,15966,77771.0,72300.0,81688.0,253444284,2081335384,1931886,15865036,57553,56
2622,2023,2023-07-30,사계절_데님셋업,22845,156,11111400,130450,15707,83880.0,72300.0,81688.0,358826415,2980130250,2450292,20350200,71227,45
2642,2023,2023-08-06,사계절_데님셋업,22845,85,5661607,130450,15707,88512.0,85242.0,81688.0,358826415,2980130250,1335095,11088250,66607,49
2665,2023,2023-08-13,사계절_데님셋업,22845,112,7006635,130450,15707,87346.0,85242.0,81688.0,358826415,2980130250,1759184,14610400,62559,52
2690,2023,2023-08-20,사계절_데님셋업,22845,473,30694603,130450,15707,76959.0,85242.0,81688.0,358826415,2980130250,7429411,61702850,64893,50
2717,2023,2023-08-27,사계절_데님셋업,22845,742,50514735,130450,15707,88148.0,85242.0,81688.0,358826415,2980130250,11654594,96793900,68079,48
2745,2023,2023-09-03,사계절_데님셋업,22845,194,11446455,130450,15707,64157.0,89400.0,81688.0,358826415,2980130250,3047158,25307300,59002,55
2773,2023,2023-09-10,사계절_데님셋업,26147,25,3067800,130450,16326,95784.0,89400.0,81688.0,426875922,3410876150,408150,3261250,122712,6
2803,2023,2023-09-17,사계절_데님셋업,26147,-36,-6872200,130450,16326,92215.0,89400.0,81688.0,426875922,3410876150,-587736,-4696200,190894,-46
2833,2023,2023-09-24,사계절_데님셋업,26147,728,66382185,130450,16326,95213.0,89400.0,81688.0,426875922,3410876150,11885328,94967600,91184,30
2863,2023,2023-10-01,사계절_데님셋업,26147,1070,72875532,130450,16326,86354.0,88804.0,81688.0,426875922,3410876150,17468820,139581500,68108,48
2883,2023,2023-10-08,사계절_데님셋업,26147,108,13027941,130450,16326,86436.0,88804.0,81688.0,426875922,3410876150,1763208,14088600,120629,8
2903,2023,2023-10-15,사계절_데님셋업,26147,55,7464619,130450,16326,95732.0,88804.0,81688.0,426875922,3410876150,897930,7174750,135720,-4
2923,2023,2023-10-22,사계절_데님셋업,26147,-105,-3854740,130450,16326,89302.0,88804.0,81688.0,426875922,3410876150,-1714230,-13697250,36712,72
2943,2023,2023-10-29,사계절_데님셋업,26147,44,5185600,130450,16326,86198.0,88804.0,81688.0,426875922,3410876150,718344,5739800,117855,10
2963,2023,2023-11-05,사계절_데님셋업,26147,138,9858066,130450,16326,90934.0,87782.0,81688.0,426875922,3410876150,2252988,18002100,71435,45
2983,2023,2023-11-12,사계절_데님셋업,26147,176,12361045,130450,16326,85432.0,87782.0,81688.0,426875922,3410876150,2873376,22959200,70233,46
3003,2023,2023-11-19,사계절_데님셋업,26147,31,1180250,130450,16326,87199.0,87782.0,81688.0,426875922,3410876150,506106,4043950,38073,71
3023,2023,2023-11-26,사계절_데님셋업,26147,506,23615415,130450,16326,87561.0,87782.0,81688.0,426875922,3410876150,8260956,66007700,46671,64
3039,2023,2023-12-03,사계절_데님셋업,26147,11,1479582,130450,16326,71166.0,69254.0,81688.0,426875922,3410876150,179586,1434950,134507,-3
3055,2023,2023-12-10,사계절_데님셋업,26147,4,514300,130450,16326,90246.0,69254.0,81688.0,426875922,3410876150,65304,521800,128575,1
3071,2023,2023-12-17,사계절_데님셋업,26147,-12,-2187981,130450,16326,73418.0,69254.0,81688.0,426875922,3410876150,-195912,-1565400,182332,-40
3087,2023,2023-12-24,사계절_데님셋업,26147,286,17155800,130450,16326,66924.0,69254.0,81688.0,426875922,3410876150,4669236,37308700,59985,54
3103,2023,2023-12-31,사계절_데님셋업,26147,-76,-5455360,130450,16326,56036.0,69254.0,81688.0,426875922,3410876150,-1240776,-9914200,71781,45

In [34]:
grouped_df[(grouped_df['카테고리_통합'] == '가을_캐주얼셔츠')&(grouped_df['기획년도']==2022)]

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계,실판매가,할인율
1517,2022,2022-07-10,가을_캐주얼셔츠,6654,0,0,89900,7315,NaN,66563.0,43894.0,48674010,598194600,0,0,66563,26
1533,2022,2022-07-17,가을_캐주얼셔츠,17454,0,0,89900,7880,NaN,66563.0,43894.0,137537520,1569114600,0,0,66563,26
1550,2022,2022-07-24,가을_캐주얼셔츠,17454,0,0,89900,7880,NaN,66563.0,43894.0,137537520,1569114600,0,0,66563,26
1569,2022,2022-07-31,가을_캐주얼셔츠,17454,19,1264700,89900,7880,66563.0,66563.0,43894.0,137537520,1569114600,149720,1708100,66563,26
1590,2022,2022-08-07,가을_캐주얼셔츠,17454,144,10135994,89900,7880,70345.0,60865.0,43894.0,137537520,1569114600,1134720,12945600,70389,22
1611,2022,2022-08-14,가을_캐주얼셔츠,17454,-4,-2614315,89900,7880,110668.0,60865.0,43894.0,137537520,1569114600,-31520,-359600,653579,-627
1633,2022,2022-08-21,가을_캐주얼셔츠,17454,190,8524400,89900,7880,39689.0,60865.0,43894.0,137537520,1569114600,1497200,17081000,44865,50
1655,2022,2022-08-28,가을_캐주얼셔츠,17454,321,15291627,89900,7880,47660.0,60865.0,43894.0,137537520,1569114600,2529480,28857900,47637,47
1680,2022,2022-09-04,가을_캐주얼셔츠,17454,492,22251745,89900,7880,45104.0,42830.0,43894.0,137537520,1569114600,3876960,44230800,45227,50
1707,2022,2022-09-11,가을_캐주얼셔츠,17454,1011,43129725,89900,7880,42694.0,42830.0,43894.0,137537520,1569114600,7966680,90888900,42660,53
1735,2022,2022-09-18,가을_캐주얼셔츠,17454,855,37627509,89900,7880,44020.0,42830.0,43894.0,137537520,1569114600,6737400,76864500,44009,51
1766,2022,2022-09-25,가을_캐주얼셔츠,17454,1053,41630254,89900,7880,39500.0,42830.0,43894.0,137537520,1569114600,8297640,94664700,39535,56
1797,2022,2022-10-02,가을_캐주얼셔츠,17454,1100,41847226,89900,7880,38041.0,38755.0,43894.0,137537520,1569114600,8668000,98890000,38043,58
1818,2022,2022-10-09,가을_캐주얼셔츠,17454,786,28927725,89900,7880,36813.0,38755.0,43894.0,137537520,1569114600,6193680,70661400,36804,59
1839,2022,2022-10-16,가을_캐주얼셔츠,17454,868,35439867,89900,7880,40773.0,38755.0,43894.0,137537520,1569114600,6839840,78033200,40829,55
1860,2022,2022-10-23,가을_캐주얼셔츠,17454,633,23409575,89900,7880,37312.0,38755.0,43894.0,137537520,1569114600,4988040,56906700,36982,59
1881,2022,2022-10-30,가을_캐주얼셔츠,17454,289,11777575,89900,7880,40837.0,38755.0,43894.0,137537520,1569114600,2277320,25981100,40753,55
1902,2022,2022-11-06,가을_캐주얼셔츠,17454,387,14696820,89900,7880,38036.0,33699.0,43894.0,137537520,1569114600,3049560,34791300,37976,58
1923,2022,2022-11-13,가을_캐주얼셔츠,17454,341,11494556,89900,7880,34596.0,33699.0,43894.0,137537520,1569114600,2687080,30655900,33708,63
1944,2022,2022-11-20,가을_캐주얼셔츠,17454,376,10981605,89900,7880,29360.0,33699.0,43894.0,137537520,1569114600,2962880,33802400,29206,68
1965,2022,2022-11-27,가을_캐주얼셔츠,17454,234,7674600,89900,7880,32802.0,33699.0,43894.0,137537520,1569114600,1843920,21036600,32797,64

In [35]:
grouped_df[(grouped_df['카테고리_통합'] == '여름_점퍼')&(grouped_df['기획년도']==2021)]

,기획년도,주차,카테고리_통합,총입고수량,판매수량,판매액,평균택가,평균원가,주차별_평균_실판매가,월별_평균_실판매가,시즌별_평균_실판매가,총입고원가,총입고택가,매출원가계,판매택가계,실판매가,할인율
72,2021,2021-02-07,여름_점퍼,8338,0,0,224000,20458,NaN,189298.0,109435.0,170578804,1867712000,0,0,189298,15
90,2021,2021-02-14,여름_점퍼,8338,48,9552000,224000,20458,199000.0,189298.0,109435.0,170578804,1867712000,981984,10752000,199000,11
109,2021,2021-02-21,여름_점퍼,8338,212,49571200,224000,20458,218464.0,189298.0,109435.0,170578804,1867712000,4337096,47488000,233826,-4
128,2021,2021-02-28,여름_점퍼,8338,471,43944961,224000,20458,121264.0,189298.0,109435.0,170578804,1867712000,9635718,105504000,93301,58
147,2021,2021-03-07,여름_점퍼,8338,821,84280781,224000,20458,98690.0,103971.0,109435.0,170578804,1867712000,16796018,183904000,102656,54
167,2021,2021-03-14,여름_점퍼,8338,953,105027018,224000,20458,109020.0,103971.0,109435.0,170578804,1867712000,19496474,213472000,110207,51
188,2021,2021-03-21,여름_점퍼,8338,949,100254786,224000,20458,104714.0,103971.0,109435.0,170578804,1867712000,19414642,212576000,105643,53
209,2021,2021-03-28,여름_점퍼,8338,884,90802900,224000,20458,103460.0,103971.0,109435.0,170578804,1867712000,18084872,198016000,102718,54
231,2021,2021-04-04,여름_점퍼,8338,561,58043000,224000,20458,108248.0,103563.0,109435.0,170578804,1867712000,11476938,125664000,103463,54
253,2021,2021-04-11,여름_점퍼,8338,495,49763600,224000,20458,106352.0,103563.0,109435.0,170578804,1867712000,10126710,110880000,100533,55
275,2021,2021-04-18,여름_점퍼,8338,424,40999550,224000,20458,98244.0,103563.0,109435.0,170578804,1867712000,8674192,94976000,96697,57
297,2021,2021-04-25,여름_점퍼,8338,157,14989000,224000,20458,101408.0,103563.0,109435.0,170578804,1867712000,3211906,35168000,95471,57
319,2021,2021-05-02,여름_점퍼,8338,180,18135700,224000,20458,108458.0,96618.0,109435.0,170578804,1867712000,3682440,40320000,100754,55
341,2021,2021-05-09,여름_점퍼,8338,90,9140019,224000,20458,113376.0,96618.0,109435.0,170578804,1867712000,1841220,20160000,101556,55
363,2021,2021-05-16,여름_점퍼,8338,-75,-6446000,224000,20458,74632.0,96618.0,109435.0,170578804,1867712000,-1534350,-16800000,85947,62
385,2021,2021-05-23,여름_점퍼,8338,306,23369000,224000,20458,93218.0,96618.0,109435.0,170578804,1867712000,6260148,68544000,76369,66
407,2021,2021-05-30,여름_점퍼,8338,-28,-2684050,224000,20458,93407.0,96618.0,109435.0,170578804,1867712000,-572824,-6272000,95859,57
422,2021,2021-06-06,여름_점퍼,8338,69,6771000,224000,20458,108091.0,102456.0,109435.0,170578804,1867712000,1411602,15456000,98130,56
437,2021,2021-06-13,여름_점퍼,8338,-15,-2116250,224000,20458,124464.0,102456.0,109435.0,170578804,1867712000,-306870,-3360000,141083,37
452,2021,2021-06-20,여름_점퍼,8338,33,2204850,224000,20458,72271.0,102456.0,109435.0,170578804,1867712000,675114,7392000,66814,70
467,2021,2021-06-27,여름_점퍼,8338,18,1722000,224000,20458,105000.0,102456.0,109435.0,170578804,1867712000,368244,4032000,95667,57
482,2021,2021-07-04,여름_점퍼,8338,4,396000,224000,20458,109000.0,108750.0,109435.0,170578804,1867712000,81832,896000,99000,56
500,2021,2021-07-11,여름_점퍼,8338,12,1287000,224000,20458,103500.0,108750.0,109435.0,170578804,1867712000,245496,2688000,107250,52
519,2021,2021-07-18,여름_점퍼,8338,8,822000,224000,20458,114000.0,108750.0,109435.0,170578804,1867712000,163664,1792000,102750,54
538,2021,2021-07-25,여름_점퍼,8338,-10,-921000,224000,20458,108500.0,108750.0,109435.0,170578804,1867712000,-204580,-2240000,92100,59
558,2021,2021-08-01,여름_점퍼,8338,6,522291,224000,20458,103829.0,118194.0,109435.0,170578804,1867712000,122748,1344000,87048,61
580,2021,2021-08-08,여름_점퍼,8338,7,573000,224000,20458,81857.0,118194.0,109435.0,170578804,1867712000,143206,1568000,81857,63
602,2021,2021-08-15,여름_점퍼,8338,18,1260200,224000,20458,70011.0,118194.0,109435.0,170578804,1867712000,368244,4032000,70011,69
627,2021,2021-08-22,여름_점퍼,8338,24,808100,224000,20458,62955.0,118194.0,109435.0,170578804,1867712000,490992,5376000,33671,85
652,2021,2021-08-29,여름_점퍼,8338,22,3112500,224000,20458,230060.0,118194.0,109435.0,170578804,1867712000,450076,4928000,141477,37
682,2021,2021-09-05,여름_점퍼,8338,26,2169100,224000,20458,85187.0,95768.0,109435.0,170578804,1867712000,531908,5824000,83427,63
712,2021,2021-09-12,여름_점퍼,8338,25,2445450,224000,20458,97348.0,95768.0,109435.0,170578804,1867712000,511450,5600000,97818,56
742,2021,2021-09-19,여름_점퍼,8338,48,3889476,224000,20458,94266.0,95768.0,109435.0,170578804,1867712000,981984,10752000,81031,64
772,2021,2021-09-26,여름_점퍼,8338,48,4192000,224000,20458,106272.0,95768.0,109435.0,170578804,1867712000,981984,10752000,87333,61